apiVersion: apps/v1
kind: Deployment
metadata:
  name: valaxy-rtp
  namespace: valaxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  valaxy-rtp
  template:
    metadata:
      labels:
        app:  valaxy-rtp
    spec:
      imagePullSecrets:
      - name: jfrogcred
      containers:
      - name:  valaxy-rtp
        image: solodevops1.jfrog.io/valaxy-docker-local/ttrend:2.1.5
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
